// <auto-generated />
using System;
using BGMDevamsizlik.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BGMDevamsizlik.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BGMDevamsizlik.Models.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Derss");
                });

            modelBuilder.Entity("BGMDevamsizlik.Models.Devamsizlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<long>("TCKimlikNo")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Zamani")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Devamsizliks");
                });

            modelBuilder.Entity("BGMDevamsizlik.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.Property<long>("TCKimlikNo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("BGMDevamsizlik.Models.Sinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SinifAdi")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sinifs");
                });
#pragma warning restore 612, 618
        }
    }
}
